version: '2'
services:

  fish-registry:
    image: fish-registry
    container_name: fish-registry
    build:
      context: ./fish-registry/target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8000:8000

  fish-config:
    image: fish-config
    container_name: fish-config
    build:
      context: ./fish-config/target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8010:8010

  fish-auth:
    image: fish-auth
    container_name: fish-auth
    build:
      context: ./fish-auth/fish-auth-server/target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8020:8020

  fish-admin:
    image: fish-admin
    container_name: fish-admin
    build:
      context: ./fish-admin/fish-admin-server/target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8100:8100

  fish-gateway:
    image: fish-gateway
    container_name: fish-gateway
    build:
      context: ./fish-gateway/target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8080:8080
